workflows:
  ios-build:
    name: iOS Build Ad-Hoc
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

      vars:
        
        XCODE_WORKSPACE: "Runner"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.abarei.semjuros"

    scripts:
      - name: Instalar dependências
        script: flutter pub get

      - name: Print Generated.xcconfig
        script: |
          cat ios/Flutter/Generated.xcconfig || echo "Arquivo não encontrado"

      - name: Inicializar keychain
        script: keychain initialize

      - name: Restaurar certificado e perfil
        script: |
          # Restaurar certificado a partir do Base64
          echo $P12_BASE64 | base64 --decode > /tmp/semjuroscert.p12
          scripts:
      
      - name: Baixar e adicionar certificado
        script: |
           curl -L https://raw.githubusercontent.com/ASKTERIX2024/semjuros/main/ios/semjurosbuildios.p12 -o /tmp/semjurosbuildios.p12
           keychain add-certificates --certificate /tmp/semjurosbuildios.p12 --certificate-password raqVCujx
      
      - name: Baixar e instalar provisioning profile
          script: |
            curl -L https://raw.githubusercontent.com/ASKTERIX2024/semjuros/main/ios/SemJurosBuildAlien.mobileprovision -o /tmp/SemJurosBuildAlien.mobileprovision
            mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
            cp /tmp/SemJurosBuildAlien.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
   
      - name: Ajustar plataforma iOS e instalar CocoaPods
        script: |
          cd ios
          if [ -f "Podfile" ]; then
            # Adiciona a linha se não existir
            grep -q "^platform :ios" Podfile || echo "platform :ios, '13.0'" >> Podfile
          fi
          pod install
     
      - name: Verificar se o workspace existe
        script: |
          ls "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE.xcworkspace" || {
            echo "Workspace não encontrado!" && exit 1
          }

      - name: Gerar ExportOptions.plist
        script: |
          cat <<EOF > $CM_BUILD_DIR/ios/export_options.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
          "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
            <dict>
              <key>method</key>
              <string>ad-hoc</string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>signingCertificate</key>
              <string>Apple Distribution</string>
              <key>provisioningProfiles</key>
              <dict>
                <key>com.abarei.semjuros</key>
                <string>SemJurosBuild</string>
              </dict>
              <key>compileBitcode</key>
              <false/>
            </dict>
          </plist>
          EOF

      - name: Build IPA usando comando simplificado
        script: |
          set -eo pipefail
          xcodebuild \
            -workspace "ios/Runner.xcworkspace" \
            -scheme "Runner" \
            -archivePath "$CM_BUILD_DIR/ios/Runner.xcarchive" \
            archive \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            CODE_SIGN_STYLE=Manual \
            | tee xcodebuild.log

      - name: Mostrar log do XcodeBuild
        script: cat xcodebuild.log

artifacts:
  - build/ios/ipa/*.ipa
