workflows:
  ios-ad-hoc-build:
    name: iOS Ad-Hoc Workflow
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        CERTIFICATE_PASSWORD: Aba531Rei#@
    scripts:
      - name: Instalar dependências
        script: |
          flutter pub get

      - name: Importar certificado P12
        script: |
          security create-keychain -p "codemagic" build.keychain
          security import SemJuros_novo.p12 -k build.keychain -P $CERTIFICATE_PASSWORD -A
          security list-keychains -s build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "codemagic" build.keychain

      - name: Build IPA para Ad-Hoc
        script: |
          flutter build ipa --export-method ad-hoc

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - alberto@abarei.com
        notify:
          success: true
          failure: true